### ISSUE TITLE
margin, padding  meses ups slider action

### ISSUE THREAD

**Issue by pusuarigth** [domsleee/JQuery-Range-Slider#2]
I am pretty newbie at writing html, when i try to place the slider using padding or margins the cursor gets messed up. When I place 3 sliders the first one seem to work fine,  the next ones doesn't when I  use the mouse to move its pointer it moves with a offset from the mouse pointer. 

I don't know which css attributes i could use to place the slider other than default left aligned

thanks

**Comment by domsleee** [comment]
Generally you use `margin:auto` to center an element relative to its parent, and `float:right` or absolute positioning inside a wrapper element to align a div to the right.

The behaviour where the offset was messed up is probably related to a bug where the position of the cursor was calculated relative to the first relatively-positioned ancestor instead of the viewport. This is fixed recently in ed93e25

I've added alignment examples to [the live demo](https://domsleee.github.io/JQuery-Range-Slider/)

**Comment by pusuarigth** [comment]
thank you very much for answering. first I was using absolute position with no  luck then tried margin or padding to do the same.  thanks for the fix and the examples in the demo.
